version: '3.9'
services:
  app:
    build:
      context: .
      target: builder
    tty: true
    env_file:
      - .env
    # networks:
    #   - app_network
    environment:
      - TZ=Asia/Tokyo
      - DATABASE_URL=db
      # - NODE_ENV=
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:15.3
    hostname: db
    # networks:
    #   - app_network
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=next-prisma-sample
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d
    # env_file:
    # - .env
    ports:
      - '5432:5432'
# networks:
#   app_network:
#     driver: bridge
volumes:
  node_modules:
